language: minimal

services:
  - docker

deploy:
  - provider: script
    skip_cleanup: true
    script: Docker/travis/deploy-on-branch.sh
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: Docker/travis/deploy-on-tag.sh
    on:
      tags: true
